// THIS FILE IS AN EXAMPLE OF THE CONFIG.JS FILE NEEDED FOR THIS SITE TO RUN
// FOR THIS SITE TO WORK YOU NEED TO CREATE A CONFIG.JS FILE AND FILL IT WITH THE FOLLOWING LINES
// SUBSTITUTING THE BLANK STRINGS WITH YOUR OWN TMDB API INFORMATION

const TMDB_API_KEY = "xxxxxxxxxxxxxxxxxxxxx";
const ACCESS_TOKEN_AUTH = "xxxxxxxxxxxxxxxxxxxxxxx";

export { TMDB_API_KEY, ACCESS_TOKEN_AUTH };